version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - CONFIG_PATH=/app/config/config.yaml
      - MIGRATIONS_DIR=/app/migrations
    volumes:
      - ./config:/app/config
      - ./migrations:/app/migrations  # Монтируем папку с миграциями

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=coins
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d coins"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: